version: "3.9"
   
services:
  backend:
    restart: unless-stopped
    env_file:
    - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    networks:
      - backend-net
    depends_on:

  frontend:
    restart: unless-stopped
    env_file:
    - ./frontend/.env
    ports:
      - "3000:3000"
    build:
      context: ./frontend
      dockerfile: Dockerfile
networks:
  backend-net:
    name: backend-net